[package]
name = "viso"
version = "0.1.0"
edition = "2018"
authors = ["Matt Clement <m@nullroute.host>"]
description = "1Password Terminal UI"
readme = "README.md"
license = "MIT"

[dependencies]
tui = "0.8.0"
termion = "1.5.5"
failure = "0.1.6"
serde_json = "1.0.45"
